```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidymodels)
library(spData)
library(ggpmisc)
```

```{r}
redlining = read_csv(here::here("discussion", "data", "redlining.csv")) %>% 
  left_join(us_states_df %>% rename(name = state)) %>% 
  janitor::clean_names()
```

### Data Splitting

```{r}
set.seed(123)

split <- initial_split(redlining, prop = 0.7)

train <- training(split)
test <- testing(split)

# Generate validation data
folds <- vfold_cv(train, v = 5, repeats = 2)
```

### Recipe Specification

```{r}
recipe <- recipe(percent ~ region + area + total_pop_10 + median_income_10 + poverty_level_10, data = train) %>%
  step_normalize(all_numeric_predictors()) %>% 
  step_integer(all_nominal_predictors()) %>% 
  step_interact(terms = ~total_pop_10:median_income_10) %>% 
  step_interact(terms = ~total_pop_10:poverty_level_10) %>% 
  step_interact(terms = ~poverty_level_10:median_income_10) 
```

### Model: Tuned Linear Regression

```{r}
lm_model <- linear_reg(penalty = tune(), mixture = tune()) %>% 
  set_engine("glmnet") %>% 
  set_mode("regression")

lm_model
```

```{r}
lm_wflw <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(recipe)

lm_wflw
```

```{r}
# Use tune_grid()
lm_cv_tune <- lm_wflw %>% 
  tune_grid(resamples = folds, grid = 5)
```


```{r}
# Use collect_metrics()
collect_metrics(lm_cv_tune)
```

```{r}
autoplot(lm_cv_tune) +
  theme_bw() +
  labs(x = "Parameter value",
       y = "Performance metric")
```


#### Finalize workflow

```{r}
lm_best <- show_best(lm_cv_tune, n =1, metric = "rmse")
lm_best
```

```{r}
lm_final <- finalize_workflow(lm_wflw, select_best(lm_cv_tune, metric = "rmse"))
lm_final

```

### Model Fitting

```{r}
 # fit the data to the training data
lm_fit <- fit (lm_final, train)
```

```{r}
train_predict <- predict(lm_fit, train) %>% 
  bind_cols(train)

test_predict <- predict(lm_fit, test) %>% 
  bind_cols(test)
```

```{r}
train_metrics <- train_predict %>% 
  metrics(percent, .pred)
train_metrics

test_metrics <- test_predict %>% 
  metrics(percent, .pred)
test_metrics

```

### Visualization

```{r}
ggplot(test_predict, aes(x = percent, y = .pred)) +
  geom_point() +
  stat_poly_line()
```

